### ISSUE TITLE
Error when checking for new version

### ISSUE THREAD

**Issue by anselhelm** [arturekdev/mineOres#1]
Good day,

Using mineOres 1.2, the following message appears whenever the plugin checks for updates:

[Server thread/INFO]:  Error for check new version: mineOres
[Server thread/INFO]:  Error: java.io.FileNotFoundException: https://arturekdev.github.io/mineOres/mineOres.html

This is on a Spigot 1.16.5 server.

**Comment by arturekdev** [comment]
Hi, check now.

**Comment by anselhelm** [comment]
Thanks for the reply. How do I manually check whether this is working? Do I need to download or update or was something else causing an issue? (Apologies if the answers are self-evident.)

**Comment by arturekdev** [comment]
Something else caused this issue.

**Comment by anselhelm** [comment]
Ah. In that case, I can report that I've not seen it happen since whatever you did. I'll close this now :)
